# Site Configuration
name: "SekaiMoe"
avatar: "/avatar.jpg"
background: "/background.png"
bio: "我萌故我在！"
buttonColor: "#fdd3e4"

# Social Links
workLinks:
  - name: "Github"
    url: "https://github.com/dabao1955"
    icon: "Github"
  - name: "Email"
    url: "mailto:dabao1955@163.com"
    icon: "Mail"

funLinks:
  - name: "Discord"
    url: "https://discord.gg/dabao1955"
    icon: "DiscIcon"

